package com.nukkad.common.audit;

public enum AuditAction {
    LOGIN, LOGOUT, CREATE_IDEA, UPDATE_IDEA, DELETE_IDEA, CREATE_STARTUP,
    CREATE_OPPORTUNITY, APPLY_OPPORTUNITY, INVESTOR_INTRODUCTION, ADMIN_ACTION,
    ADMIN_USER_STATUS_CHANGED, ADMIN_USER_ROLE_CHANGED, ADMIN_REPORT_RESOLVED,
    ADMIN_CONTENT_REMOVED, ADMIN_CONTENT_RESTORED, ADMIN_CONTENT_APPROVED, ADMIN_CONTENT_REJECTED,
    WALLET_ADMIN_ADJUSTMENT, PAYMENT_INITIATED, PAYMENT_SUCCEEDED, PAYMENT_FAILED,
    WALLET_WITHDRAWAL_REQUESTED, WALLET_WITHDRAWAL_APPROVED, WALLET_WITHDRAWAL_REJECTED,
    WALLET_STATUS_CHANGED, INVESTOR_ACTIVATION_APPROVED, INVESTOR_ACTIVATION_REJECTED
}
