package com.nukkad.common.audit;

public enum AuditAction {
    LOGIN, LOGOUT, CREATE_IDEA, UPDATE_IDEA, DELETE_IDEA, CREATE_STARTUP,
    CREATE_OPPORTUNITY, APPLY_OPPORTUNITY, INVESTOR_INTRODUCTION, ADMIN_ACTION
}
