ALTER TABLE user_social_links
  MODIFY COLUMN platform ENUM('LINKEDIN','GITHUB','PORTFOLIO','TWITTER','KAGGLE','LEETCODE','BEHANCE','DRIBBBLE','MEDIUM',
                               'INSTAGRAM','YOUTUBE','STACKOVERFLOW','DEVTO','PRODUCTHUNT','HUGGINGFACE') NOT NULL;
