CREATE TABLE user_section_privacy (
  user_id    CHAR(36) NOT NULL,
  section    ENUM('EXPERIENCE','EDUCATION','ACHIEVEMENTS','PROJECTS','CERTIFICATIONS','PUBLICATIONS','SOCIAL_LINKS','RECOMMENDATIONS') NOT NULL,
  visibility ENUM('PUBLIC','CONNECTIONS','PRIVATE') NOT NULL DEFAULT 'PUBLIC',
  PRIMARY KEY (user_id, section),
  CONSTRAINT fk_user_section_privacy_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
