-- audit_logs.action is a native MySQL ENUM (see V59/V69/V71's comment on why this column needs
-- widening on every new AuditAction literal). Adds the literal for admin freeze/unfreeze of a
-- wallet.

ALTER TABLE audit_logs
    MODIFY COLUMN action ENUM(
        'LOGIN','LOGOUT','CREATE_IDEA','UPDATE_IDEA','DELETE_IDEA','CREATE_STARTUP',
        'CREATE_OPPORTUNITY','APPLY_OPPORTUNITY','INVESTOR_INTRODUCTION','ADMIN_ACTION',
        'ADMIN_USER_STATUS_CHANGED','ADMIN_USER_ROLE_CHANGED','ADMIN_REPORT_RESOLVED',
        'ADMIN_CONTENT_REMOVED','ADMIN_CONTENT_RESTORED','ADMIN_CONTENT_APPROVED','ADMIN_CONTENT_REJECTED',
        'WALLET_ADMIN_ADJUSTMENT','PAYMENT_INITIATED','PAYMENT_SUCCEEDED','PAYMENT_FAILED',
        'WALLET_WITHDRAWAL_REQUESTED','WALLET_WITHDRAWAL_APPROVED','WALLET_WITHDRAWAL_REJECTED',
        'WALLET_STATUS_CHANGED'
    ) NOT NULL;
