-- The admin-managed investor catalog (V88) is audit-logged: ADMIN_INVESTOR_CREATED, ADMIN_INVESTOR_UPDATED,
-- ADMIN_INVESTOR_DELETED, ADMIN_INVESTOR_INTRO_CLOSED. audit_logs.action is a native MySQL ENUM (see V59/V78/
-- V79/V80/V81/V87 for why every new AuditAction literal needs its own migration), so widen it with the four new
-- events. No table or data change: existing rows and every existing literal are untouched.

ALTER TABLE audit_logs
    MODIFY COLUMN action ENUM(
        'LOGIN','LOGOUT','CREATE_IDEA','UPDATE_IDEA','DELETE_IDEA','CREATE_STARTUP',
        'CREATE_OPPORTUNITY','APPLY_OPPORTUNITY','INVESTOR_INTRODUCTION','ADMIN_ACTION',
        'ADMIN_USER_STATUS_CHANGED','ADMIN_USER_ROLE_CHANGED','ADMIN_REPORT_RESOLVED',
        'ADMIN_CONTENT_REMOVED','ADMIN_CONTENT_RESTORED','ADMIN_CONTENT_APPROVED','ADMIN_CONTENT_REJECTED',
        'WALLET_ADMIN_ADJUSTMENT','PAYMENT_INITIATED','PAYMENT_SUCCEEDED','PAYMENT_FAILED',
        'WALLET_WITHDRAWAL_REQUESTED','WALLET_WITHDRAWAL_APPROVED','WALLET_WITHDRAWAL_REJECTED',
        'WALLET_STATUS_CHANGED','INVESTOR_ACTIVATION_APPROVED','INVESTOR_ACTIVATION_REJECTED',
        'ADMIN_PASSWORD_RESET_REQUESTED','ADMIN_PASSWORD_RESET_COMPLETED','ADMIN_PASSWORD_CHANGED',
        'WALLET_PIN_SET','WALLET_PIN_CHANGED','WALLET_PIN_RESET','WALLET_PIN_LOCKED',
        'ADMIN_RESOURCE_CREATED','ADMIN_RESOURCE_UPDATED','ADMIN_RESOURCE_DELETED',
        'ADMIN_STARTUP_CREATED',
        'ADMIN_INVESTOR_CREATED','ADMIN_INVESTOR_UPDATED','ADMIN_INVESTOR_DELETED','ADMIN_INVESTOR_INTRO_CLOSED'
    ) NOT NULL;
